### ISSUE TITLE
Error while installing dependencies when creating a new project

### ISSUE THREAD

**Issue by ralcar** [PolymerX/polymerx-cli#8]
During the "installing dependencies...cli.js create [template] [dest]", i get this error message and it stops.

Node Version: 9.4.0
npm: 5.3.0

`{ Error: Command failed: npm install
nullnull
    at makeError (C:\Users\Znipe\AppData\Roaming\npm\node_modules\polymerx-cli\node_modules\execa\index.js:169:9)
    at Promise.all.then.arr (C:\Users\Znipe\AppData\Roaming\npm\node_modules\polymerx-cli\node_modules\execa\index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 4294963248,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  killed: false }`

**Comment by LasaleFamine** [comment]
Hi @ralcar, thank you for reporting this one.

Actually I knew we have some problems on Windows, and this needs to be investigated.

**Comment by LasaleFamine** [comment]
The problem should be fixed with the `0.0.3` release.

Please @ralcar, reopen this issue if you have this problem still. Thank you!
